### ISSUE TITLE
deform_conv.cc:24:61: fatal error: third_party/eigen3/unsupported/Eigen/CXX11/Tensor: No such file or directory

### ISSUE THREAD

**Issue by Zealoe** [Zardinality/TF-deformable-conv#2]
face a problem when   ./g++_complie.sh
（I use anaconda and i have setted the tensorflow dir）

the error information is as below：

deform_conv.cc:24:61: fatal error: third_party/eigen3/unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
                                                             ^
compilation terminated.

how can i fix it？Thanks！

**Comment by Zardinality** [comment]
Hey @Zealoe , what is your `$TF_INC`? When you run `g++_compile.sh`, it should be printed in your shell. Make sure the directory indicated by `$TF_INC` have a `third_party` folder.

**Comment by Zealoe** [comment]
@Zardinality Thanks for your reply. But I have met another problem. Now if I import ib.deform_conv_op as deform_conv_op,then it will throw undefined symbol error. So i use deform_conv_op=tf.load_op_library() .
But it throw the error as below



Traceback (most recent call last):
  File "test_deform_conv.py", line 21, in <module>
    grad = tf.gradients(result, [a, b, c])
  File "/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 534, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'DeformConvOp' (op type: DeformConvOp)

**Comment by Zealoe** [comment]
@Zardinality can you give me your Wechat account if available? thanks very much.

**Comment by Zealoe** [comment]
@Zardinality   I have fixed the problem, thanks.
and there is a small bug in the readme part. the TF_INC in the changing part of g++_compile.sh should follow a $ symbol, or it will throw the " No such file or directory " error

**Comment by Zardinality** [comment]
@Zealoe Did you mean [the first line](https://github.com/Zardinality/TF-deformable-conv/blob/master/lib/g%2B%2B_complie.sh)? It runs well with bash. By the way, if any potential bug you encountered prevents you from running the demo with different version of tensorflow and python, you are welcomed to start a pull request: )
