### ISSUE TITLE
what's the meaning of the offset if the values are larger than the image scale?

### ISSUE THREAD

**Issue by Zealoe** [Zardinality/TF-deformable-conv#4]
the loss has gotten diverged and the values of offset are very large. So i don't understand the meaning of the current offset.. do you have any idea?

**Comment by Zardinality** [comment]
If the offset is larger than the scale of the current image, then the corresponding coordinate will be clipped to the image scale, refer to [here](https://github.com/Zardinality/TF-deformable-conv/blob/master/lib/deform_conv.cu.cc#L98).

**Comment by Zealoe** [comment]
thanks very much!
